services:
  app:
    build:
      context: ./server
      dockerfile: cmd/Dockerfile
    ports:
      - "${APPROVAL_WEBSERVER_PORT}:${APPROVAL_WEBSERVER_PORT}"
    volumes:
      - ./server:/app
      - ./data:/app/data
    command: go run cmd/main.go
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
