services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APPROVAL_WEBSERVER_PORT}:${APPROVAL_WEBSERVER_PORT}"
    volumes:
      - .:/app
    command: go run main.go types.go handlers.go websockets.go reviewstore.go
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APPROVAL_WEBSERVER_PORT=${APPROVAL_WEBSERVER_PORT}
    networks:
      - app-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=${APPROVAL_API_BASE_URL}
      - VITE_WEBSOCKET_BASE_URL=${APPROVAL_WEBSOCKET_BASE_URL}
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
