services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: ./server
      dockerfile: cmd/Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${APPROVAL_WEBSERVER_PORT}:${APPROVAL_WEBSERVER_PORT}"
    volumes:
      - ./server:/app
    command: go run cmd/main.go
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - app-network

  computer-use-demo:
    build:
      context: ../anthropic-quickstarts/computer-use-demo
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      # Core application code
      - ../anthropic-quickstarts/computer-use-demo/computer_use_demo:/home/computeruse/computer_use_demo
      
      # Individual script files from image/
      - ../anthropic-quickstarts/computer-use-demo/image/entrypoint.sh:/home/computeruse/entrypoint.sh
      - ../anthropic-quickstarts/computer-use-demo/image/http_server.py:/home/computeruse/http_server.py
      - ../anthropic-quickstarts/computer-use-demo/image/index.html:/home/computeruse/index.html
      - ../anthropic-quickstarts/computer-use-demo/image/mutter_startup.sh:/home/computeruse/mutter_startup.sh
      - ../anthropic-quickstarts/computer-use-demo/image/novnc_startup.sh:/home/computeruse/novnc_startup.sh
      - ../anthropic-quickstarts/computer-use-demo/image/start_all.sh:/home/computeruse/start_all.sh
      - ../anthropic-quickstarts/computer-use-demo/image/tint2_startup.sh:/home/computeruse/tint2_startup.sh
      - ../anthropic-quickstarts/computer-use-demo/image/x11vnc_startup.sh:/home/computeruse/x11vnc_startup.sh
      - ../anthropic-quickstarts/computer-use-demo/image/xvfb_startup.sh:/home/computeruse/xvfb_startup.sh
      
      # Directories from image/
      - ../anthropic-quickstarts/computer-use-demo/image/computer_use_demo:/home/computeruse/computer_use_demo_image
      - ../anthropic-quickstarts/computer-use-demo/image/static_content:/home/computeruse/static_content
      
      # Hidden directories
      - ../anthropic-quickstarts/computer-use-demo/image/.anthropic:/home/computeruse/.anthropic
      - ../anthropic-quickstarts/computer-use-demo/image/.cache:/home/computeruse/.cache
      - ../anthropic-quickstarts/computer-use-demo/image/.config:/home/computeruse/.config
      - ../anthropic-quickstarts/computer-use-demo/image/.streamlit:/home/computeruse/.streamlit
      
      # Original .anthropic config
      - $HOME/.anthropic:/home/computeruse/.anthropic_host

    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - G_SLICE=always-malloc
      - DISPLAY=:1
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_SERVER_ADDRESS=0.0.0.0
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
