services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: ./server
      dockerfile: cmd/Dockerfile
    ports:
      - "${APPROVAL_WEBSERVER_PORT}:${APPROVAL_WEBSERVER_PORT}"
    volumes:
      - ./server:/app
    command: go run cmd/main.go
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - app-network

  computer-use-demo:
    build:
      context: ../anthropic-quickstarts/computer-use-demo
      dockerfile: Dockerfile
    volumes:
      - ../anthropic-quickstarts/computer-use-demo/computer_use_demo:/home/computeruse/computer_use_demo
      - $HOME/.anthropic:/home/computeruse/.anthropic
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - G_SLICE=always-malloc
      - DISPLAY=:1
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_BROWSER_SERVER_ADDRESS=0.0.0.0
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
